# -*- coding: utf-8 -*-
"""california_housing_pricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFZQS96hUX4j_wdaFU5uOBo7xvoqmlFw

Import Libraries:
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Machine learning libraries:"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import  r2_score, mean_absolute_error, mean_squared_error

"""Load Dataset"""

from sklearn import datasets
df = datasets.fetch_california_housing()
print(df)
x = pd.DataFrame(df.data, columns=df.feature_names)
y = df.target

"""Correlation Heatmap:"""

plt.figure(figsize=(10,8))
sns.heatmap(x.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

"""Feature Distribution Plots"""

x.hist(bins=20, figsize=(15,10))
plt.suptitle("Feature Distributions")
plt.show()

"""Train-Test Split"""

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, shuffle=True,random_state=42)

"""Model Training

XGBRegressor Algorithms
"""

XGB_model = XGBRegressor()

XGB_model.fit(x_train, y_train)

"""Train Performance:"""

y_pred = XGB_model.predict(x_train)
score = r2_score(y_train,y_pred)
score1=mean_absolute_error(y_train,y_pred)
score2=mean_squared_error(y_train,y_pred)
print(score*100)
print(score1)
print(score2)

"""Test Performance:"""

y_pred = XGB_model.predict(x_test)
score = r2_score(y_test,y_pred)
score1=mean_absolute_error(y_test,y_pred)
score2=mean_squared_error(y_test,y_pred)
print(score*100)
print(score1)
print(score2)

Li_model = LinearRegression()

Li_model.fit(x_train,y_train)

y_pred = Li_model.predict(x_train)
score = r2_score(y_train,y_pred)
score1=mean_absolute_error(y_train,y_pred)
score2=mean_squared_error(y_train,y_pred)
print(score*100)
print(score1)
print(score2)

y_pred = Li_model.predict(x_test)
score = r2_score(y_test,y_pred)
score1=mean_absolute_error(y_test,y_pred)
score2=mean_squared_error(y_test,y_pred)
print(score*100)
print(score1)
print(score2)